name: PR Check

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            build_cmd: npm run build:linux
          - os: windows-latest
            build_cmd: npm run build:win

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: npm

      - run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: ${{ matrix.build_cmd }}
